---
name: learn-github-actions
on: 
  push:
    branches:    
      - 'test'
    paths:
      - "testfolder/**"
    
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ls